apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: buildah-
spec:
  params: 
    - name: app-name
      value: express-sample-app
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/ting-tekton-express
    - name: image-repo
      value: quay.io/jm_carnicero/express-assignment
  pipelineRef:
    name: buildah
  serviceAccountName: build-robot
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce 
        resources:
          requests:
            storage: 1Gi
  - name: git-ops-repo
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
        - ReadWriteOnce
  - name: mycredentials
    secret:
      secretName: mycredentials-github
